language: java
sudo: false

jdk:
- oraclejdk8

env:
  global:
  - secure: "xYQjQqJkLcj9krT35oub2Z2Y5PQlpWIz6LGt84P6nx4s/o6q0T0GUWWi+JxiHkVd/0AWtk5DjSEDPqct4IqhlElWa6FETqC20ZbVXNMD2I2E+V1EVO0Pkp/udIUqTx/I3uHp40ESasYr3pMGQs1tfTCARimu3xbIP/3bkXcFNYCPbuG43AtxKwrzFrxce0FZLmzK1nhOau2x2FijdLHYgmO7yiSYR6iNcgmU4x65z1KmjqYXNinHxpCTE1Uk1r93K1Q9ugXGI4s8lM4Iy7QLriCTnyIVRCVBWQ/xUWw29QlGlGh31hCYiFli3N8W4S7+p9ivJyZ3PTjImu+uLtAViKQCpEZZfUP3UcxaD1RMhA8Cyk1ALz4dV2HMgxuuHo2xKyajdwuQAX4QckVEavCEDZ5B/ZhzbjDxHLVvKGYc1Se6RcQL0xG/r7ui2dHp18E/8TpItWccHQpfPfe1yL0s9hRdkwN9QpAe3Xpns7YK1R3A/7Wnm8ScQ4q8/60VVD2q260fKFZU3a+7yFInTKGX4jSY+U/Iy4pFQ2N71sUHjKXXsY/tJUd9HpRO6vOUXY4TuGt3nz8cXvPAR9z7LgSYwnC2n1K786urpntJ+0mXmkpxZo83e5zwLZk5s2U69zs00J2m0Gs9SKLxN5b7QKVddrr8SjxD+D+UgCj8ZaBPDCc="
  - secure: "Plnb8IUddJb744B5DT5mNDuVkAbUeCCT5durHg735jj410HLf3qTDpRQMXfzNTUzxcC5TbEj4/4w0zup7ED5yUQocOlko+DR2uYcSLsLYCdF9KzhRlQ8RvMChLD1h+WbNzvG8Ck8EjJ7oRTtXy6hkmSd1nH9mIXYHMRR+bya3B59zRS1K3z4r0tPYRRozXw6C38KKwdEOiZZ36Li+jmo+5MauUIEosyo3N27F9KqVs2qwt7oM3hs5h1lswreM3Rqp9FQOLCEgy18QkIvo94BMXdGZWUzb4XpfefNRVf+WKE0cs6eYCqsi/8ASwFNyTpnQnXOpwfc7Yw1a1ZMckx4gDBjWaVQtFc2pFobINH21odKMPN9b3B5PHGtUL4xgV8LQzF7dkDjPUzRRXgPC65pM+0hg71U7D445MWLzCygzRpzj0mRkfzEA9edDivmxI8yRwgvSHDd+3CY2cDaAclN2VKu5o3Cabge6m2+VtBpRCHna2rkDJWgBLPU3YABan2x4TeEXnqTpkgXkOwcyuF5O5qcqVpfL5Q/G0XaGtEDvLVpTrA4fHtS0pSNu9pPTb/z7GVjiiIT7S0LCSEbPvI8IorAZU1x7U1HCCsg//PJjWqadb4fGAhWwWXUr3VINASL4nr2FtpKUS0j/mo7Y/hp4AQrqW4inL5cjCNkzpoy5Sw="
  matrix:
  - TERM=dumb

before_install:
- cp gradle.properties.ci gradle.properties

script:
- JAVA_OPTS="-Xmx384m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -noverify" ./gradlew check -Dcheckstyle=disable

after_success:
- "./gradlew coveralls"
- "./gradlew uploadArchives"

matrix:
  fast_finish: true

cache:
  directories:
  - "$HOME/.gradle"
