language: java
sudo: false

jdk:
- oraclejdk8

env:
  matrix:
  - TERM=dumb
  global:
    secure: "R58E/r2yZWbgVceCRGOC9tdY8fEU/dEtPIzNxd1nwYTiZjLp5b20mqtV47PX3zndRSdYw41G97VOiCeUEojZQSAy2jN2kpFmWbBBprVWUNUAWgDaDGoKTSbP08MBjXv2k8/DYZV8FDc1G9EZgPDIR/FC3AT4D+1zJeAd6R1ukWIPC+4ma4LpkP1PcXhnkTIEbYB+GfOJeEOTkowdpjEaaKhXgN7c6iADmIsYtnFvpHSnhsVp/lv09lTJNZXCEwa9P/Gz3hjAVg6bL7q0OY9qhRXU8exJLhK9W8+bUJnmxNXgLVwdn2GNr+6ZftnG7Hv6oEVWVKCeCS9Mksii8wrmwrjQ1Mr4ubnFrH6XLAok2PtcB8sE0sI7XkeQj2TyxoDpac1Q+CuS9ne/c9n93Ow62GBOw3vEEbegXCZK5hqtDNGuh3BiElg5dtB22W+xDskG5AHrcEvtWobKTEas/eIysTmdSvbk1n6T5KSKRNSqDMsf7MNKNyMzhFff2xJW7JSelYVw4ygjPgLI4gNxqlm+PYKgi0+l4s78GAto35FLpCUQMuM6FxQpXDeH6QRCoBHbfMNDACYbHIyS6dMM/cHJQkcN/O7lFVophfnoxP3fdPsjfMXePpr9H7oXBusgLfgtwB3UH5u3eGt9RWAjCvyoba44qDMKx0KqegvKqvzbQjY="
    secure: "g8XQ7qDXmpN88vYwWTc/Ubnu4l25uKIXpMCjybKn6wtYbZ/PGJcqFivag3Jwylgli/kcZU8royXljgcOFVfifdZYAyMOeQwqHy3OhRUf87fho8OlISuNzEa/jMrtSIQ3AhU4Zawn/SoT3uq1lBT8MW+YQeGsNzRG1jGsZ+lnyul9+dPVr+MV9+fpnKJAdpJ7W66QabfNHr3sA22AsX1vgK3an1RXtx9i9aGqVtI/p38VOQ8pgHNTBoPg768BYSff9vO78Rv+7KqoXAO0N3sWu+VyJDvXc7agfUHAS9aH6CeP7TDV1Ea71RI9FVheUVkrId0aMMt0fHuMV+fv8i2BcUYZXPlCNFjT8rUVvPzXrA3R28cxy7vrHMSRqBG1FZuiNdw8fxMhDkl5QaLfEoAMteIW2kTbPfOAQQnvPccpo84QhM1gUvM1LB2yV1QRtRKnBiBvkd7cc206Rk7GODrQubG+jSdp+IsBr/P1o495Q3oMl+qdLykfbTZaTyu1lZqLw8b2lVglRxpAuT6GhWL02Aw+I5RidpNbqW0qhUfkwrGvFc8q9cOOFqaUD9chNLzl9bKFIgymfN+2zsAidxcVJGK+u6sM47CLCjkP+BCOKXPXiAS8wxqPBm2aHp+kmgFhBgWMyOkcMcsrHDOd54cbRqbdOTD+LXhLxchrnComgK0="

before_install:
- cp gradle.properties.ci gradle.properties

script:
- JAVA_OPTS="-Xmx384m -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=0 -noverify" ./gradlew check

after_success:
- "./gradlew coveralls uploadArchives -PnexusUsername='${SONATYPE_USERNAME}' -PnexusPassword='${SONATYPE_PASSWORD}'"

matrix:
  fast_finish: true

cache:
  directories:
  - "$HOME/.gradle"
